### ISSUE TITLE
Not able to change the version from dropdown

### ISSUE THREAD

**Issue by hafizasadabbas** [notum-cz/strapi-plugin-content-versioning#91]
### Steps to reproduce the behavior

1. Go to 'Any version'
2. Click on the 'change to version dropdown'
3. Scroll down to 'options'
4. You will not able to select any option

### Expected behavior

The select dropdown should work.

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version:  v16
- NPM version:8.19.4
- Strapi version: 4.11.1
- Database: postgres
- Operating system: mac

**Comment by omikulcik** [comment]
Hi @hafizasadabbas, I have also encountered this problem. Our main goal right now is to solve the patch package problem but I believe this should be fixed as well and hopefully we will find time needed to investigate what is causing this behaviour. I am adding the good first issue tag as it seems relatively simple if anyone wants to contribute by fixing this.

**Comment by Thomas-T** [comment]
the problem is easy to fix :
const selectedVersion = data.find((v) => v.versionNumber === value);
versionNumber is a number and value a string
remove === for == or do a parseInt(value) will fix

**Comment by omikulcik** [comment]
We have just released a new version on NPM in which this should be fixed as #90 was merged. So I am closing this issue.

**Comment by hafizasadabbas** [comment]
It's not fixed yet. I am sharing the console error for a better understanding 
**Cannot read properties of undefined (reading 'id')** The error is thrown when I click on some selection from the dropdown.

created a patch with const selectedVersion = data.find((v) => v.versionNumber == Number(value));
But it's not working.
